### ISSUE TITLE
Flakey tests

### ISSUE THREAD

**Issue by jacobbednarz** [Homebrew/homebrew-bundle#361]
While starting a patch for #359, I hit a couple of inconsistently failing specs.

```
$ bundle && bundle exec rake spec
Using rake 10.4.2
Using bundler 1.16.3
Using json 1.8.3
Using docile 1.1.5
Using simplecov-html 0.10.0
Using simplecov 0.11.1
Using url 0.3.2
Using codecov 0.1.10
Using diff-lcs 1.3
Using rspec-support 3.7.1
Using rspec-core 3.7.1
Using rspec-expectations 3.7.0
Using rspec-mocks 3.7.0
Using rspec 3.7.0
Using unindent 1.0
Bundle complete! 5 Gemfile dependencies, 15 gems now installed.
Use `bundle info [gemname]` to see where a bundled gem is installed.
(in /usr/local/Homebrew/Library/Taps/homebrew/homebrew-bundle)
/Users/jacob/.rbenv/versions/2.3.7/bin/ruby -I/Users/jacob/.rbenv/versions/2.3.7/lib/ruby/gems/2.3.0/gems/rspec-core-3.7.1/lib:/Users/jacob/.rbenv/versions/2.3.7/lib/ruby/gems/2.3.0/gems/rspec-support-3.7.1/lib /Users/jacob/.rbenv/versions/2.3.7/lib/ruby/gems/2.3.0/gems/rspec-core-3.7.1/exe/rspec --pattern spec/\*\*\{,/\*/\*\*\}/\*_spec.rb

Randomized with seed 23776
.................................................F............................F.......................................................F...........................

Failures:

  1) Bundle::Commands::Cleanup there are casks to uninstall uninstalls casks
     Failure/Error: Kernel.system "brew", "cask", action, "--force", *casks

       Kernel received :system with unexpected arguments
         expected: ("brew", "cask", "uninstall", "--force", "a", "b")
              got: ("brew", "cask", "zap", "--force", "a", "b")
     # ./lib/bundle/commands/cleanup.rb:28:in `run'
     # ./spec/cleanup_command_spec.rb:90:in `block (4 levels) in <top (required)>'
     # ./spec/cleanup_command_spec.rb:90:in `block (3 levels) in <top (required)>'
     # ./spec/spec_helper.rb:41:in `block (3 levels) in <top (required)>'
     # ./spec/spec_helper.rb:41:in `block (2 levels) in <top (required)>'

  2) Bundle::BrewInstaller.formula_installed_and_up_to_date? returns result
     Failure/Error: expect(Bundle::BrewInstaller.formula_installed_and_up_to_date?("foo")).to eql(true)

       expected: true
            got: false

       (compared using eql?)
     # ./spec/brew_installer_spec.rb:145:in `block (3 levels) in <top (required)>'
     # ./spec/spec_helper.rb:41:in `block (3 levels) in <top (required)>'
     # ./spec/spec_helper.rb:41:in `block (2 levels) in <top (required)>'

  3) Bundle::BrewDumper#formula_oldnames works
     Failure/Error: expect(Bundle::BrewDumper.formula_oldnames["aold"]).to eql "homebrew/versions/a"

       expected: "homebrew/versions/a"
            got: nil

       (compared using eql?)
     # ./spec/brew_dumper_spec.rb:645:in `block (3 levels) in <top (required)>'
     # ./spec/spec_helper.rb:41:in `block (3 levels) in <top (required)>'
     # ./spec/spec_helper.rb:41:in `block (2 levels) in <top (required)>'

Finished in 9.71 seconds (files took 2.07 seconds to load)
162 examples, 3 failures

Failed examples:

rspec ./spec/cleanup_command_spec.rb:88 # Bundle::Commands::Cleanup there are casks to uninstall uninstalls casks
rspec ./spec/brew_installer_spec.rb:144 # Bundle::BrewInstaller.formula_installed_and_up_to_date? returns result
rspec ./spec/brew_dumper_spec.rb:626 # Bundle::BrewDumper#formula_oldnames works

Randomized with seed 23776

Coverage report generated for RSpec to /usr/local/Homebrew/Library/Taps/homebrew/homebrew-bundle/coverage. 1780 / 1794 LOC (99.22%) covered.
/Users/jacob/.rbenv/versions/2.3.7/bin/ruby -I/Users/jacob/.rbenv/versions/2.3.7/lib/ruby/gems/2.3.0/gems/rspec-core-3.7.1/lib:/Users/jacob/.rbenv/versions/2.3.7/lib/ruby/gems/2.3.0/gems/rspec-support-3.7.1/lib /Users/jacob/.rbenv/versions/2.3.7/lib/ruby/gems/2.3.0/gems/rspec-core-3.7.1/exe/rspec --pattern spec/\*\*\{,/\*/\*\*\}/\*_spec.rb failed
```

```
$ bundle && bundle exec rake spec
Using rake 10.4.2
Using bundler 1.16.3
Using json 1.8.3
Using docile 1.1.5
Using simplecov-html 0.10.0
Using simplecov 0.11.1
Using url 0.3.2
Using codecov 0.1.10
Using diff-lcs 1.3
Using rspec-support 3.7.1
Using rspec-core 3.7.1
Using rspec-expectations 3.7.0
Using rspec-mocks 3.7.0
Using rspec 3.7.0
Using unindent 1.0
Bundle complete! 5 Gemfile dependencies, 15 gems now installed.
Use `bundle info [gemname]` to see where a bundled gem is installed.
(in /usr/local/Homebrew/Library/Taps/homebrew/homebrew-bundle)
/Users/jacob/.rbenv/versions/2.3.7/bin/ruby -I/Users/jacob/.rbenv/versions/2.3.7/lib/ruby/gems/2.3.0/gems/rspec-core-3.7.1/lib:/Users/jacob/.rbenv/versions/2.3.7/lib/ruby/gems/2.3.0/gems/rspec-support-3.7.1/lib /Users/jacob/.rbenv/versions/2.3.7/lib/ruby/gems/2.3.0/gems/rspec-core-3.7.1/exe/rspec --pattern spec/\*\*\{,/\*/\*\*\}/\*_spec.rb

Randomized with seed 25377
..................................................................................................................................................................

Finished in 8.76 seconds (files took 0.23214 seconds to load)
162 examples, 0 failures

Randomized with seed 25377

Coverage report generated for RSpec to /usr/local/Homebrew/Library/Taps/homebrew/homebrew-bundle/coverage. 1794 / 1794 LOC (100.0%) covered.
```

```
$ bundle && bundle exec rake spec
Using rake 10.4.2
Using bundler 1.16.3
Using json 1.8.3
Using docile 1.1.5
Using simplecov-html 0.10.0
Using simplecov 0.11.1
Using url 0.3.2
Using codecov 0.1.10
Using diff-lcs 1.3
Using rspec-support 3.7.1
Using rspec-core 3.7.1
Using rspec-expectations 3.7.0
Using rspec-mocks 3.7.0
Using rspec 3.7.0
Using unindent 1.0
Bundle complete! 5 Gemfile dependencies, 15 gems now installed.
Use `bundle info [gemname]` to see where a bundled gem is installed.
(in /usr/local/Homebrew/Library/Taps/homebrew/homebrew-bundle)
/Users/jacob/.rbenv/versions/2.3.7/bin/ruby -I/Users/jacob/.rbenv/versions/2.3.7/lib/ruby/gems/2.3.0/gems/rspec-core-3.7.1/lib:/Users/jacob/.rbenv/versions/2.3.7/lib/ruby/gems/2.3.0/gems/rspec-support-3.7.1/lib /Users/jacob/.rbenv/versions/2.3.7/lib/ruby/gems/2.3.0/gems/rspec-core-3.7.1/exe/rspec --pattern spec/\*\*\{,/\*/\*\*\}/\*_spec.rb

Randomized with seed 10077
.......................................................................................F...........................................................F..............

Failures:

  1) Bundle::Commands::Cleanup there are casks to uninstall uninstalls casks
     Failure/Error: Kernel.system "brew", "cask", action, "--force", *casks

       Kernel received :system with unexpected arguments
         expected: ("brew", "cask", "uninstall", "--force", "a", "b")
              got: ("brew", "cask", "zap", "--force", "a", "b")
     # ./lib/bundle/commands/cleanup.rb:28:in `run'
     # ./spec/cleanup_command_spec.rb:90:in `block (4 levels) in <top (required)>'
     # ./spec/cleanup_command_spec.rb:90:in `block (3 levels) in <top (required)>'
     # ./spec/spec_helper.rb:41:in `block (3 levels) in <top (required)>'
     # ./spec/spec_helper.rb:41:in `block (2 levels) in <top (required)>'

  2) Bundle::BrewDumper#formula_oldnames works
     Failure/Error: expect(Bundle::BrewDumper.formula_oldnames["aold"]).to eql "homebrew/versions/a"

       expected: "homebrew/versions/a"
            got: nil

       (compared using eql?)
     # ./spec/brew_dumper_spec.rb:645:in `block (3 levels) in <top (required)>'
     # ./spec/spec_helper.rb:41:in `block (3 levels) in <top (required)>'
     # ./spec/spec_helper.rb:41:in `block (2 levels) in <top (required)>'

Finished in 7.83 seconds (files took 0.22913 seconds to load)
162 examples, 2 failures

Failed examples:

rspec ./spec/cleanup_command_spec.rb:88 # Bundle::Commands::Cleanup there are casks to uninstall uninstalls casks
rspec ./spec/brew_dumper_spec.rb:626 # Bundle::BrewDumper#formula_oldnames works

Randomized with seed 10077

Coverage report generated for RSpec to /usr/local/Homebrew/Library/Taps/homebrew/homebrew-bundle/coverage. 1787 / 1794 LOC (99.61%) covered.
/Users/jacob/.rbenv/versions/2.3.7/bin/ruby -I/Users/jacob/.rbenv/versions/2.3.7/lib/ruby/gems/2.3.0/gems/rspec-core-3.7.1/lib:/Users/jacob/.rbenv/versions/2.3.7/lib/ruby/gems/2.3.0/gems/rspec-support-3.7.1/lib /Users/jacob/.rbenv/versions/2.3.7/lib/ruby/gems/2.3.0/gems/rspec-core-3.7.1/exe/rspec --pattern spec/\*\*\{,/\*/\*\*\}/\*_spec.rb failed
```

I haven't had a chance to dive into these just yet but I wanted to record this to take a look and not have it forgotten. A preliminary assumptions suggests either a leaky test or a order dependant test.

**Comment by MikeMcQuaid** [comment]
Odd, I've not seen this. If you get the chance to dive in that'd be great 👍

**Comment by colindean** [comment]
I'll give it a shot, @jacobbednarz. 

Are you seeing failures reliably with the _same seeds_?

* Failure: 23776, 10077
* Success: 25377

I kinda doubt that rspec's randomizer is at play here, though.

**Comment by jacobbednarz** [comment]
Yep, the same seeds are consistently failing.

**Comment by jacobbednarz** [comment]
Steps to reproduce (from my machine):

- `cd $(brew --repository)/Library/Taps/homebrew/homebrew-bundle`
- `bundle install`
- `bundle exec rspec --seed 23776`

**Comment by colindean** [comment]
I'm able to reproduce the failure and success patterns with those same seeds. Neat. I'll see what I can do.

**Comment by colindean** [comment]
I'm quickly identifying at least one of the problems.

When I run 

    bundle exec rspec -f d --seed 23776 ./spec/cleanup_command_spec.rb

the test

```
Bundle::Commands::Cleanup
…
  there are casks to uninstall
    uninstalls casks (FAILED - 1)
```

is run last and fails. With seed 10077, it runs _second_ to last and fails. Looking at the failure message:

```
1) Bundle::Commands::Cleanup there are casks to uninstall uninstalls casks
     Failure/Error: Kernel.system "brew", "cask", action, "--force", *casks

       Kernel received :system with unexpected arguments
         expected: ("brew", "cask", "uninstall", "--force", "a", "b")
              got: ("brew", "cask", "zap", "--force", "a", "b")
```

it seems that `zap` is somehow getting into the env for that test. Looking _around_ the two related test contexts – "there are casks to uninstall" and "there are casks to zap" – I see this:

https://github.com/Homebrew/homebrew-bundle/blob/bc97597d437f32712791d5b68d558da1798d34e1/spec/cleanup_command_spec.rb#L102

When I comment out that line and install a `skip()` in the text in that context, other tests in that file pass reliably.

So, that's the culprit for that consistent failure that seems to be the result of an order-dependent context setup.

**Comment by colindean** [comment]
Next up!

When I run `bundle exec rspec -f d --seed 23776`, I see two failures:

```
Failures:

  1) Bundle::BrewInstaller.formula_installed_and_up_to_date? returns result
     Failure/Error: expect(Bundle::BrewInstaller.formula_installed_and_up_to_date?("foo")).to eql(true)

       expected: true
            got: false

       (compared using eql?)
     # ./spec/brew_installer_spec.rb:145:in `block (3 levels) in <top (required)>'
     # ./spec/spec_helper.rb:41:in `block (3 levels) in <top (required)>'
     # /Users/colin/.rvm/gems/ruby-2.3.1/gems/bundler-1.16.1/lib/bundler.rb:297:in `block in with_clean_env'
     # /Users/colin/.rvm/gems/ruby-2.3.1/gems/bundler-1.16.1/lib/bundler.rb:540:in `with_env'
     # /Users/colin/.rvm/gems/ruby-2.3.1/gems/bundler-1.16.1/lib/bundler.rb:297:in `with_clean_env'
     # ./spec/spec_helper.rb:41:in `block (2 levels) in <top (required)>'

  2) Bundle::BrewDumper#formula_oldnames works
     Failure/Error: expect(Bundle::BrewDumper.formula_oldnames["aold"]).to eql "homebrew/versions/a"

       expected: "homebrew/versions/a"
            got: nil

       (compared using eql?)
     # ./spec/brew_dumper_spec.rb:645:in `block (3 levels) in <top (required)>'
     # ./spec/spec_helper.rb:41:in `block (3 levels) in <top (required)>'
     # /Users/colin/.rvm/gems/ruby-2.3.1/gems/bundler-1.16.1/lib/bundler.rb:297:in `block in with_clean_env'
     # /Users/colin/.rvm/gems/ruby-2.3.1/gems/bundler-1.16.1/lib/bundler.rb:540:in `with_env'
     # /Users/colin/.rvm/gems/ruby-2.3.1/gems/bundler-1.16.1/lib/bundler.rb:297:in `with_clean_env'
     # ./spec/spec_helper.rb:41:in `block (2 levels) in <top (required)>'
```

When I run _just_ the installer spec with

    bundle exec rspec -f d --seed 23776 ./spec/brew_installer_spec.rb

The test passes! Same deal with the 10077 seed: two failures, but the installer spec passes when run alone.

Now the fun part: when I run the dumper spec with those two seeds, it passes with both!

So, some test somewhere else is modifying the environment that these two failing tests need.

I have a feeling…

```
$ rg 'ARGV <<'
spec/list_command_spec.rb
38:          options_list.each { |opt| ARGV << opt }
```

Messed with that a little bit, commenting out that line, skipping the nearby test, or commenting out the entire context. No dice, bad hunch.

Let's try running the two together.

    bundle exec rspec -f d --seed 23776 ./spec/brew_dumper_spec.rb ./spec/brew_installer_spec.rb

One failure:

```
Failures:

  1) Bundle::BrewDumper#formula_oldnames works
     Failure/Error: expect(Bundle::BrewDumper.formula_oldnames["aold"]).to eql "homebrew/versions/a"

       expected: "homebrew/versions/a"
            got: nil

       (compared using eql?)
     # ./spec/brew_dumper_spec.rb:645:in `block (3 levels) in <top (required)>'
     # ./spec/spec_helper.rb:41:in `block (3 levels) in <top (required)>'
     # /Users/colin/.rvm/gems/ruby-2.3.1/gems/bundler-1.16.1/lib/bundler.rb:297:in `block in with_clean_env'
     # /Users/colin/.rvm/gems/ruby-2.3.1/gems/bundler-1.16.1/lib/bundler.rb:540:in `with_env'
     # /Users/colin/.rvm/gems/ruby-2.3.1/gems/bundler-1.16.1/lib/bundler.rb:297:in `with_clean_env'
     # ./spec/spec_helper.rb:41:in `block (2 levels) in <top (required)>'
```

When the dumper spec runs before installer spec, it's OK: `bundle exec rspec -f d --seed 1 ./spec/brew_dumper_spec.rb ./spec/brew_installer_spec.rb`.

Interestingly, after some mucking around, I found that commenting out the dumper reset here:

https://github.com/Homebrew/homebrew-bundle/blob/bc97597d437f32712791d5b68d558da1798d34e1/spec/brew_installer_spec.rb#L118-L121

Triggers the installer spec failure regardless of the order of the two tests, leading me to believe that the reset is behaving poorly.

So, two options are in my head, both of which seem like a lot of work:

1. Continue poking around to see if I can resolve this ordering problem
1. Refactor BrewDumper, making it an instantiated class instead of a module with state.

Out of time for tonight but hopefully these notes will inspire someone else, including me in a few days.
